### ISSUE TITLE
I found An API for Visual Studio C# To extract data from excel files

### ISSUE THREAD

**Issue by GZMaster** [edla4eva/result_and_transcript_system#9]
https://www.c-sharpcorner.com/article/read-excel-file-in-web-api-using-c-sharp/

this is the link to the link to the api for visual studio c#, that can take data form an excel file and store it a database.

**Comment by edla4eva** [comment]
Great. This is helpful

**Comment by edla4eva** [comment]
Kindly put the library in the third party folder.  We actually need two of such library.

**Comment by GZMaster** [comment]
alright sir, I will do it as fast as possible

**Comment by GZMaster** [comment]
alright sir, I will do it as fast as possible
